DROP DATABASE IF EXISTS practica;
CREATE DATABASE practica;
USE practica;

DROP TABLE IF EXISTS usuarios;
CREATE TABLE usuarios(
id_usuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nombre_completo VARCHAR(255) NOT NULL,
numero_identificacion VARCHAR(50) NOT NULL UNIQUE,
correo VARCHAR(100) DEFAULT NULL,
telefono VARCHAR(30) DEFAULT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS libros;
CREATE TABLE libros(
isbn VARCHAR(50) NOT NULL PRIMARY KEY,
titulo VARCHAR(255) NOT NULL,
anio_publicacion YEAR DEFAULT NULL,
autor VARCHAR(100) DEFAULT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS prestamos;
CREATE TABLE prestamos(
id_prestamo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_usuario INT,
isbn VARCHAR(50),
fecha_prestamo DATE NOT NULL,
fecha_devolucion DATE DEFAULT NULL,
estado ENUM('entregado', 'retrasado', 'activo') DEFAULT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (isbn) REFERENCES libros (isbn) ON DELETE SET NULL ON UPDATE CASCADE
);